[project]
name = "maieutic-backend"
version = "0.1.0"
description = "The backend of maieutic"
requires-python = ">=3.12"

dependencies = [
    "fastapi>=0.141.1",
    "uvicorn[standard]>=0.53.0",
    "openai>=3.17.0",
    "dotenv>=0.9.9",
    "tavily-python>=0.8.4",
    "pytest>=9.1.1",
    "loguru>=0.7.3",
    "pytest-asyncio>=1.4.0",
]
